### ISSUE TITLE
Demo 2 Use Cases

### ISSUE THREAD

**Issue by michaelrosstarr** [COS301-SE-2023/Avalanche#108]
- [x] Domain Watch
- [ ] Registrar Integration
- [x] Transaction Dashboard
~~- [ ] User Preferences ~~
- [ ] User Group Management
- [ ] Data Product Subscription

**Comment by michaelrosstarr** [comment]
For registrar information, i can just do a call do the API and show the response, unless @markbr02 would rather do that on backend and just show them that way, either by video or request.

**Comment by markbr02** [comment]
That has been done, already from backend side, and it adds their info into postgres, we can integrate it if you want. With user preferences, for now we can keep it on the backend
