### ISSUE TITLE
Sometimes graphs get loaded in twice

### ISSUE THREAD

**Issue by GT-GillesTeuwen** [COS301-SE-2023/Avalanche#145]
All graphs have been loaded in twice here. Notice Yearly, from 2018-05-25 to 2023-05-25 in both pictures

![Image](https://user-images.githubusercontent.com/103629800/248579075-c637a9ed-86b6-4e42-96a9-7550922b6f63.png)

======================

======================

![Image](https://user-images.githubusercontent.com/103629800/248579087-bf478207-e6d9-47ea-bce1-6ff06380436a.png)

**Comment by michaelrosstarr** [comment]
What environment are you running in?

**Comment by GT-GillesTeuwen** [comment]
As in?

**Comment by GT-GillesTeuwen** [comment]
Env files? Browser? Login state?

**Comment by michaelrosstarr** [comment]
Like did you run `yarn dev` or did you `yarn build` and `yarn start` it?

**Comment by GT-GillesTeuwen** [comment]
I see, I'm pretty sure it was yarn dev
