### ISSUE TITLE
Implement redis user management

### ISSUE THREAD

**Issue by markbr02** [COS301-SE-2023/Avalanche#16]
Inge, Gilles and Mark:

- [x] Implement the cache for redis
- [x] What to cache
- [x] When to cache

Mark and Michael:

- [x] Implement the user documents when registering
- [x] Time to live 24 hours
- [x] OTP lives here
- [x] If verified push to postgre and delete in document

**Comment by LiamBurgess18015001** [comment]
money machine go brrr
