### ISSUE TITLE
Filtering Graphs/Dashboards

### ISSUE THREAD

**Issue by Inge505** [COS301-SE-2023/Avalanche#160]
![Image](https://user-images.githubusercontent.com/91600439/250529818-a1b6a577-37a3-42f2-83ae-87cd25cd7856.jpeg)

![Image](https://user-images.githubusercontent.com/91600439/250530135-5977dd6b-0a95-4d69-8c07-7dbb6858d205.jpeg)

**Comment by michaelrosstarr** [comment]
Almost done, must just do the built in ones.
