### ISSUE TITLE
Frontend for custom dashboard

### ISSUE THREAD

**Issue by markbr02** [COS301-SE-2023/Avalanche#165]
- [x] Allow users to save and add their dashboard with the graphs, look at contract for info on graphs
- [x] Allow users to edit a specific dashboard
- [ ] Allow users to comment on a specific graph on a specific dashboard

**Comment by michaelrosstarr** [comment]
* an array of graph objects
* list of warehouses, and the type (the string after the warehouse, `zarc/this_right_here`, @markbr02 i need a list please
