### ISSUE TITLE
Toggle for filter

### ISSUE THREAD

**Issue by Inge505** [COS301-SE-2023/Avalanche#178]

**Comment by michaelrosstarr** [comment]
@Inge505 sorry, I forgot what this was again 🫠 do you remember

**Comment by Inge505** [comment]
Very good question.... @GT-GillesTeuwen @markbr02 any ideas?
Might have been the true false thing?? But I doubt...

**Comment by GT-GillesTeuwen** [comment]
Maybe to remove filters all at once?

**Comment by markbr02** [comment]
yeah it was that

**Comment by michaelrosstarr** [comment]
Remove filters as in?
