### ISSUE TITLE
Some weird bugs in Watch

### ISSUE THREAD

**Issue by Inge505** [COS301-SE-2023/Avalanche#190]
Very bad photos... But anyways

![Image](https://github.com/COS301-SE-2023/Avalanche/assets/91600439/3197c4bd-db6e-419c-bb91-eb2be81894b4)

![Image](https://github.com/COS301-SE-2023/Avalanche/assets/91600439/5635959c-6925-4330-bd43-a715d861a901)

**Comment by GT-GillesTeuwen** [comment]
Should be fixed now

It was a one liner... sigh
