### ISSUE TITLE
Legend for Registrar yearly transactions looks cluttered

### ISSUE THREAD

**Issue by GT-GillesTeuwen** [COS301-SE-2023/Avalanche#206]
![Image](https://user-images.githubusercontent.com/103629800/256648312-972e860e-12dc-4edf-9cf2-92c68794ab37.png)

**Comment by michaelrosstarr** [comment]
Nothing we can do, just Chart being Chart

**Comment by GT-GillesTeuwen** [comment]
Changed to Apex
