### ISSUE TITLE
Sending passwords as plaintext? Uhhhhh... That's a not a good

### ISSUE THREAD

**Issue by GT-GillesTeuwen** [COS301-SE-2023/Avalanche#285]
![Image](https://user-images.githubusercontent.com/103629800/263606467-c733da21-551b-40ae-9c56-1d59551212c6.png)

Pls fix

**Comment by GT-GillesTeuwen** [comment]
Day 1 of asking @michaelrosstarr to implement our "iron-clad" security.

**Comment by bilalmirza74** [comment]
![image](https://github.com/COS301-SE-2023/Avalanche/assets/84387676/cd532dc4-ac3c-4943-a0b5-8ca8088247f7)

this might fix for production
