### ISSUE TITLE
Internal Feedback

### ISSUE THREAD

**Issue by michaelrosstarr** [COS301-SE-2023/Avalanche#319]
- [x] #321
- [x] System theme default => making modes funny... maybe just remove dark mode
- [x] #322
- [x] QBee off navbar
- [x] Chart names
- [x] #329
- [x] #323
- [x] #325
- [x] Rejected requests, not pulse forever
- [x] Payload warning when registrar = Individual (Inge/Mark/Michael)
- [x] Fix integration login, UI funky
- [x] Blue list in colour not yellow (Inge)
- [x] Grafana (Michael/Mark)
- [x] #330
- [x] #324
- [x] #327
- [x] #326
- [x] #331
- [x] #328
- [x] ZACR keeps crashing with TypeError: Cannot read properties of null (reading 'getPeerCertificate')

**Comment by Inge505** [comment]
- [x] Remove net movement graph with registrar codes
